version: "3"
services:
  # nginx-proxy-manager:
  #   container_name: nginx-proxy-manager
  #   image: "jc21/nginx-proxy-manager:latest"
  #   restart: unless-stopped
  #   ports:
  #     - "81:81"
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./data:/data
  #     - ./letsencrypt:/etc/letsencrypt
  #   environment:
  #     SSL_ACTIVE: 1
  api_pap:
    container_name: api_pap
    image: "andresousadotpt/api_pap:4.3"
    restart: unless-stopped
    ports:
      - "8011:8000"
    environment:
      SSL_ACTIVE: 1
  frontend:
    container_name: frontend
    image: "andresousadotpt/andresousa.pt:2.0"
    restart: unless-stopped
    ports:
      - "8010:3000"
    environment:
      APP_ENV: production
      SSL_ACTIVE: 1
  db:
    container_name: db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      # So you don"t have to use root, but you can if you like
      MYSQL_USER: "andresousa"
      # You can use whatever password you like
      MYSQL_PASSWORD: "DBPASSWORD"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "DBPASSWORD"
      MYSQL_ROOT_HOST: "%"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    # Where our data will be persisted
    volumes:
      - ./database:/var/lib/mysql

networks:
  default:
    external:
      name: andresousa.pt
